### PR TITLE
Update on test environment, shared namespaces

### PR DESCRIPTION
**Pull request by PatrickLang**
Responding to @yujuhong's questions

### CODE REVIEW

**Comment by yujuhong** [comment]
> Responding to @yujuhong's questions

Thanks! Why is this in michmike's fork though?

**Comment by PatrickLang** [comment]
When he merges this will show up in the Kubernetes/enhancements PR automatically

**Comment by PatrickLang** [comment]
We're trying this as a different strategy now so there's just 1 final PR with multiple commits as needed during the final review

**Comment by yujuhong** [comment]
I see. It is hard to track all the PRs

**Comment by PatrickLang** [comment]
Yeah, definitely something to consider as we refine the KEP process. On the other hand - if something goes too long without merging then all comments are hidden as stale :/

**Pull request merged**
